### ISSUE TITLE
Repo name beginning with dash is tricky for Mac/Unix users?

### ISSUE THREAD

**Issue by daj** [Kakon24/-OmegaLambda#53]
I cloned the repo and then tried to `cd` into the directory, and my first few attempts failed (even using tab to autocomplete the folder name):
```
$ cd -omegalambda/
-bash: cd: -o: invalid option
cd: usage: cd [-L|-P] [dir]
$ cd \-omegalambda/
-bash: cd: -o: invalid option
cd: usage: cd [-L|-P] [dir]
$ cd "-omegalambda"
-bash: cd: -o: invalid option
cd: usage: cd [-L|-P] [dir]
```
I had to search the internet to find [a way to do it](https://stackoverflow.com/a/45116075/112705):
```
cd "./-omegalambda"
```
It might be nice to change the repo name to not begin with a dash, or update the README (unless you are deliberately trying to screen out inexperienced people).

I'm using the default Terminal app on macOS Mohave 10.14.6.

**Comment by Michael-Reefe** [comment]
Thank you for your feedback!  This has actually been a known issue for a while with this repository, and it seems to affect all platforms, not just MacOS.  So, we have been debating whether to change the name for a while now, and I agree that I think we do need to.  We will be looking into it.

Also, if you don't mind me asking, why did you clone our repository?  We were just wondering about the potential interest in our project.

**Comment by daj** [comment]
>why did you clone our repository?

The repo was mentioned in [The MOON newsletter](https://sites.google.com/view/georgemasonobservatory/newsletter-archive?authuser=0), and I was just curious to see what your code was like.  I was planning to pull the code and run the unit tests.  Unfortunately, the README didn't tell me how to run tests, or anything about the project, so that's where I stopped. 😄
